# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1009, 726)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.wcloud = QtWidgets.QLabel(self.centralwidget)
        self.wcloud.setScaledContents(True)
        self.wcloud.setObjectName("wcloud")
        self.verticalLayout_5.addWidget(self.wcloud)
        self.freq = QtWidgets.QLabel(self.centralwidget)
        self.freq.setScaledContents(True)
        self.freq.setObjectName("freq")
        self.verticalLayout_5.addWidget(self.freq)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1009, 29))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        self.menu_Propos = QtWidgets.QMenu(self.menubar)
        self.menu_Propos.setObjectName("menu_Propos")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOuvrir_HTML = QtWidgets.QAction(MainWindow)
        self.actionOuvrir_HTML.setObjectName("actionOuvrir_HTML")
        self.actionOuvrir_CSV = QtWidgets.QAction(MainWindow)
        self.actionOuvrir_CSV.setObjectName("actionOuvrir_CSV")
        self.actionEnregistrer_CSV = QtWidgets.QAction(MainWindow)
        self.actionEnregistrer_CSV.setObjectName("actionEnregistrer_CSV")
        self.actionEnregistrer_Worcloud = QtWidgets.QAction(MainWindow)
        self.actionEnregistrer_Worcloud.setObjectName("actionEnregistrer_Worcloud")
        self.actionEnregistrer_Fr_quences = QtWidgets.QAction(MainWindow)
        self.actionEnregistrer_Fr_quences.setObjectName("actionEnregistrer_Fr_quences")
        self.actionQuitter = QtWidgets.QAction(MainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionAide = QtWidgets.QAction(MainWindow)
        self.actionAide.setObjectName("actionAide")
        self.actionCr_ateur = QtWidgets.QAction(MainWindow)
        self.actionCr_ateur.setObjectName("actionCr_ateur")
        self.menuFichier.addAction(self.actionOuvrir_HTML)
        self.menuFichier.addAction(self.actionOuvrir_CSV)
        self.menuFichier.addAction(self.actionEnregistrer_CSV)
        self.menuFichier.addAction(self.actionEnregistrer_Worcloud)
        self.menuFichier.addAction(self.actionEnregistrer_Fr_quences)
        self.menuFichier.addAction(self.actionQuitter)
        self.menu_Propos.addAction(self.actionAide)
        self.menu_Propos.addAction(self.actionCr_ateur)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menu_Propos.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Wordcloud Stopword"))
        self.wcloud.setText(_translate("MainWindow", "Wordcloud"))
        self.freq.setText(_translate("MainWindow", "Frequence"))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier"))
        self.menu_Propos.setTitle(_translate("MainWindow", "À Propos"))
        self.actionOuvrir_HTML.setText(_translate("MainWindow", "Ouvrir HTML"))
        self.actionOuvrir_CSV.setText(_translate("MainWindow", "Ouvrir CSV"))
        self.actionEnregistrer_CSV.setText(_translate("MainWindow", "Enregistrer CSV"))
        self.actionEnregistrer_Worcloud.setText(_translate("MainWindow", "Enregistrer Nuages de mots"))
        self.actionEnregistrer_Fr_quences.setText(_translate("MainWindow", "Enregistrer Fréquences"))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter"))
        self.actionAide.setText(_translate("MainWindow", "Aide"))
        self.actionCr_ateur.setText(_translate("MainWindow", "Créateur"))

